---
apiVersion: v1
kind: Pod
metadata:
  name: aplinepod
spec:
  containers:
    - name: alpcontainer
      image: alpine:latest
      ports:
        - name: alport
          containerPort: 80
          protocol: TCP
  resources:
    requests:
      memory: 120M
      cpu: 250m
    limits:
      memory: 250M
      cpu: 1000m