### For creating namespace use the command kubectl create namespace "intended name"
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicanamespaceexp
  namespace: qa
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      name: naspace
  template:
    metadata:
      labels:
        name: naspace
    spec:
      containers:
        - name: nginxreplicas
          image: nginx:latest
          ports:
            - name: tcp
              containerPort: 80
              protocol: TCP
      resources:
        requests:
          memory: 24M
          cpu: 100m
        limits:
          memory: 128M
          cpu: 500m

#######
#Outut is like as below
#qa                   replicanamespaceexp-cmb9f                 1/1     Running   0             8m30s
#qa                   replicanamespaceexp-qcvtw                 1/1     Running   0             8m30s
#qa                   replicanamespaceexp-w5t9d                 1/1     Running   0             8m30s
#controlplane:~$ kubectl get pods --all-namespaces