---
apiVersion: v1
kind: Service
metadata:
  name: nam-svc
  namespace: qa
spec:
  ports:
    - name: serviceport
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: naspace
  type: ClusterIP